GOAT-Shoppers/muggers

server/db/models/order.js
Issue #6 
Created Order Model.
=> Finished Orders Model, no associations

server/db/models/product.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
*Your PR Notes Here*
=> completed Product model without association

server/db/models/product.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
*Your PR Notes Here*
=> added isEmpty validation to product moddel

server/db/models/lineItem.js
=> Finished LineItem Model, no associations.

server/db/models/order.js
=> Fixed Order model status to include cancelled as an option

server/api/users.js
=> Finished users route. Submitting PR

server/api/address.js, server/api/order.js
=> partial api/orders-#22

server/api/index.js, server/api/product.js
=> productRoutes

server/api/category.js, server/api/index.js, server/api/lineItem.js, server/api/product.js
=> Line item route#19

server/api/index.js, server/api/product.js, server/api/reviews.js, server/api/users.js, server/db/models/category.js, server/db/models/index.js, server/db/models/lineItem.js, server/db/models/order.js, server/db/models/product.js, server/db/models/review.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
*Your PR Notes Here*
=> Code review

server/db/models/address.js
Reverts GOAT-Shoppers/muggers#55
=> Revert "updated address model"

client/components/auth-form.js, client/components/user-home.js, client/components/user-home.spec.js, package-lock.json, package.json, server/api/users.spec.js, server/db/models/address.js, server/db/models/index.js, server/db/models/product.js, server/db/models/user.spec.js, server/db/seed.js
=> functioning seed file

server/db/models/address.js, server/db/models/index.js, server/db/seed.js
=> updated formatting for address model

server/api/product.js
=> ProductRoute-#53

server/api/index.js
=> changeINDEX.JS

server/api/category.js, server/api/index.js, server/api/lineItem.js, server/api/product.js, server/api/reviews.js, server/api/users.js, server/db/models/category.js, server/db/models/index.js, server/db/models/lineItem.js, server/db/models/product.js, server/db/models/review.js, server/db/models/user.js, server/index.js
Postman checked routes + bug fixes. No address Routes to test/check.
=> Api bug fixes

server/api/address.js, server/api/category.js, server/api/lineItem.js, server/api/order.js, server/api/reviews.js, server/api/users.js
=> Fixed eagerloading issues + added address routes

client/store/index.js, client/store/products.js
Initial reducer for product... May need additions
or close #88
=> productreducer-#88

client/components/Cart.jsx, client/components/LineItem.jsx, server/api/cart.js, server/api/index.js, server/api/order.js
Can use these to 
add lineitems
delete lineitems
modify the quantity of a lineitem
get the cart as an array as an array of objects
delete the guest cart
=> Made some backend routes to handle cart for guests.

client/components/Admin/index.js, client/components/AllProducts.jsx, client/components/DefaultHome.jsx, client/components/Review.jsx, client/components/SingleProduct.jsx, client/components/index.js, client/components/user-home.js, client/routes.js, client/store/review.js, public/style.css, server/db/seed.js
=> fixed styling and home page and seeding

client/components/AddProduct.jsx, client/components/Admin/Order.js, client/components/Admin/Product.js, client/components/Admin/User.js, client/components/AllProducts.jsx, client/components/Confirmation.jsx, client/components/DefaultHome.jsx, client/components/SingleProduct.jsx, client/components/index.js, client/components/user-home.js, client/routes.js, client/store/products.js, public/index.html, public/style.css, server/api/product.js, server/db/models/index.js
added confirmation page, styled it a bit
=> Confirmation page

client/components/AddProduct.jsx, client/components/Admin/Order.js, client/components/Admin/Product.js, client/components/Admin/User.js, client/components/AllProducts.jsx, client/components/DefaultHome.jsx, client/components/Review.jsx, client/components/SingleProduct.jsx, client/components/user-home.js, client/store/products.js, public/index.html, public/style.css, server/api/product.js, server/db/models/index.js
can add a category when creating a product!
=> Product category association

client/components/AllProducts.jsx, client/components/GuestLineItem.jsx, client/components/SingleProduct.jsx, client/components/user-home.js, client/store/lineItem.js, package.json, server/api/lineItem.js
unauthenticated user add to cart not done
=> Add to cart working for logged in user

client/components/Checkout.jsx
=> Adding fake address
